# DEPENDENCIES
markdown:       kramdown
highlighter:    rouge

# PERMALINKS
permalink:      pretty

## PAGINATE
paginate:       1

## SETUP
title:          DISCOMPLEXITY
tagline:        'TO BE SIMPLE!'
description:    'TO BE SIMPLE!'
url:            https://iticworld.github.io
baseurl:        /

author:
  name:         'Hyunsik Park'
  url:          https://twitter.com/iticworld

# CUSTOM VARS
version:        2.1.0

github:
  repo:         https://github.com/iticworld

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - old
  - TODO.md
  - note
